### ISSUE TITLE
Sets do not have keys, they have values

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-richer-keys#8]
Related to #6: although set values are unique like map keys are, they are still generally referred to as values, not keys.

In the spec so far, this only manifests unobservably:

- `keys()` and `[@@iterator]()` are defined in terms of `values()`, instead of the other way around.
- Arguments to the set methods, and intermediate variable names used in algorithms, are all "value" and not "key"

But I still think it's good to align with common understanding of how sets work.

**Comment by bmeck** [comment]
I think the counter example is that `.has(_)` works on keys for Maps and has similarity across Sets. Either way, ideally Set and Map should have some level to do this in a compatible way. The naming conventions of the spec are interesting here. Would given https://github.com/tc39/proposal-richer-keys/issues/6 it might make sense to provide both, merely because of this issue. I actually think we should move discussion back to https://github.com/tc39/proposal-richer-keys/issues/6 as it relates to multiple collection types.
